export const PRODUCTS = 'PRODUCTS';
export const GETPRODUCTS_PENDING = 'GETPRODUCTS_PENDING';
export const GETPRODUCTS_SUCCESS = 'GETPRODUCTS_SUCCESS';
export const GETPRODUCTS_ERROR = 'GETPRODUCTS_ERROR';

export const PRODUCT = 'PRODUCT';
export const GETPRODUCT_PENDING = 'GETPRODUCT_PENDING';
export const GETPRODUCT_SUCCESS = 'GETPRODUCT_SUCCESS';
export const GETPRODUCT_ERROR = 'GETPRODUCT_ERROR';

export const ADDTOCART = 'ADDTOCART';
export const ADDTOCART_SUCCESS = 'ADDTOCART_SUCCESS';

export const REMOVEFROMCART = 'REMOVEFROMCART';
export const REMOVEFROMCART_SUCCESS = 'REMOVEFROMCART_SUCCESS';

export const ORDER = 'ORDER';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';



